name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull & update submodules
        run: |
          git submodule update --init

      - name: EMSDK Version
        id: emsdk-version
        run: |
          echo "::set-output name=SHA::$(./submodules/emsdk/emsdk list | grep recommended | awk -F'[()]' '{print $2}')"
      - name: Cache EMSDK
        id: cache-emsdk
        uses: actions/cache@v3
        with:
          path: submodules/emsdk
          key: ${{ runner.os }}-c-emsdk-${{ steps.emsdk-version.outputs.SHA }}
          restore-keys: |
            ${{ runner.os }}-c-emsdk-
      - name: Update EMSDK
        if: steps.cache-emsdk.outputs.cache-hit != 'true'
        run: |
          npm run em:update

      - name: Compile SEAL
        if: steps.cache-seal.outputs.cache-hit != 'true'
        run: |
          npm run build

      - name: Save artifacts
        if: steps.cache-seal.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: seal-artifacts
          path: src/bin/
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache NPM Dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-c-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-c-node-

      - name: Install NPM Dependencies
        run: |
          npm install

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: seal-artifacts
          path: src/bin/

      - name: Transpile to JavaScript
        run: |
          npm run compile
      - name: Run tests
        run: |
          npm run test
      - name: Generate coverage report
        run: |
          npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
