name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull & update submodules
        run: |
          git submodule update --init

      - name: EMSDK Version
        id: emsdk-version
        run: |
          echo "::set-output name=SHA::$(./submodules/emsdk/emsdk list | grep recommended | awk -F'[()]' '{print $2}')"     
      # Cache EMSDK if there's no new version
      - name: Cache EMSDK
        id: cache-emsdk
        uses: actions/cache@v2.1.7
        with:
          path: submodules/emsdk
          key: ${{ runner.os }}-b-emsdk-${{ steps.emsdk-version.outputs.SHA }}
          restore-keys: |
            ${{ runner.os }}-b-emsdk-
      - name: SEAL Version
        id: seal-version
        run: |
          echo "::set-output name=SHA::$(git rev-parse HEAD:submodules/SEAL)" 
      # Cache SEAL artifacts if the commit sha didn't change
      - name: Cache SEAL
        id: cache-seal
        uses: actions/cache@v2.1.7
        with:
          path: submodules/SEAL/build
          key: ${{ runner.os }}-b-seal-${{ steps.seal-version.outputs.SHA }}
          restore-keys: |
            ${{ runner.os }}-b-seal-

      - name: Update EMSDK
        if: steps.cache-emsdk.outputs.cache-hit != 'true'
        run: |
          npm run em:update
          
      - name: Compile SEAL
        if: steps.cache-seal.outputs.cache-hit != 'true'
        run: |
          npm run build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: seal-artifacts
          path: src/bin/
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Cache NPM Dependencies
        id: cache-npm
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-b-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-b-node-
        
      - name: Install NPM Dependencies
        run: |
          npm install

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: seal-artifacts
          path: src/bin/
        
      - name: Transpile
        run: |
          npm run compile
      - name: Test
        run: |
          npm run test
