name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull & update submodules
        run: |
          git submodule update --init

      # Cache EMSDK if there's no new version
      - name: Cache EMSDK
        id: cache-emsdk
        uses: actions/cache@v2.1.7
        with:
          path: submodules/emsdk
          key: ${{ runner.os }}-b-emsdk-${{ emsdk list | grep recommended | awk -F'[()]' '{print $2}' }}
          restore-keys: |
             ${{ runner.os }}-b-emsdk-
     
      # Cache SEAL artifacts if the commit sha didn't change
      - name: Cache SEAL
        id: cache-seal
        uses: actions/cache@v2.1.7
        with:
          path: submodules/SEAL/build
          key: ${{ runner.os }}-b-seal-${{ git rev-parse HEAD:submodules/SEAL }}
          restore-keys: |
             ${{ runner.os }}-b-seal-

      - name: Update EMSDK
        if: steps.cache-emsdk.outputs.cache-hit != 'true'
        run: |
          npm run em:update
          
      - name: Compile SEAL
        if: steps.cache-seal.outputs.cache-hit != 'true'
        run: |
          npm run build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: seal-artifacts
          path: src/bin/
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      
      - name: Cache NPM Dependencies
        id: cache-npm
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-b-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-b-node-
        
      - name: Install NPM Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: seal-artifacts
          path: src/bin/
        
      - name: Transpile
        run: |
          npm run compile
      - name: Test
        run: |
          npm run test
